### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/Scam-Tripwire#1]
Layer 1:
- [ ] IFEO Based Protections
    - [ ] Action1
    - [ ] AeroAdmin
    - [ ] AnyDesk
    - [ ] AnyViewer
    - [ ] BeyondTrust
    - [ ] Chrome Remote Desktop
    - [ ] ConnectWise
    - [ ] Dameware
    - [ ] DesktopNow
    - [ ] Devolutions Remote Desktop
    - [ ] Distant Desktop
    - [ ] DWService
    - [ ] GetScreen
    - [ ] GoTo Assist
    - [ ] GoToMyPC
    - [ ] Iperius Remote
    - [ ] ISLOnline
    - [ ] Jump Desktop
    - [ ] LiteManager
    - [ ] LogMeIn
    - [ ] Microsoft Quick Assist
    - [ ] Parallels
    - [ ] RealVNC
    - [ ] RemotePC
    - [ ] Remote Utilities
    - [ ] RustDesk
    - [ ] ScreenMeet
    - [ ] Splashtop
    - [ ] Teamviewer
    - [ ] UltraVNC
    - [ ] Zoho

Layer 2:
- [ ] Applocker Based Protections
    - [ ] Action1
    - [ ] AeroAdmin
    - [ ] AnyDesk
    - [ ] AnyViewer
    - [ ] BeyondTrust
    - [ ] Chrome Remote Desktop
    - [ ] ConnectWise
    - [ ] Dameware
    - [ ] DesktopNow
    - [ ] Devolutions Remote Desktop
    - [ ] Distant Desktop
    - [ ] DWService
    - [ ] GetScreen
    - [ ] GoTo Assist
    - [ ] GoToMyPC
    - [ ] Iperius Remote
    - [ ] ISLOnline
    - [ ] Jump Desktop
    - [ ] LiteManager
    - [ ] LogMeIn
    - [ ] Microsoft Quick Assist
    - [ ] Parallels
    - [ ] RealVNC
    - [ ] RemotePC
    - [ ] Remote Utilities
    - [ ] RustDesk
    - [ ] ScreenMeet
    - [ ] Splashtop
    - [ ] Teamviewer
    - [ ] UltraVNC
    - [ ] Zoho

Layer 3:
TBD
